README.md, loader/mod_loader.gd
This is a major update:
- Adds support for loading unpacked mods without ZIPs.
- This lets you work on mods in the Godot editor, without needing to pack them into ZIPs for testing.
- This also makes ZIP filenames arbitrary, which is helpful if you release ZIPs with versioned affixes
- Loads ZIP contents into the root
- This handles importing files in your mod ZIP's `.import` folder, and matches the file system structure in the editor.
- Adds doc comments to every func.
- Optimizes the mod load process by disabling an expensive function that loops over files.
I've also updated the docs to recommend putting extender scripts in a dir named "extensions". This helps keep your mod folder tidy, as all extender scripts are separate from your mod's core files (eg `ModMain.gd`).
This update changes …
=> 2.0.0 - Add support for loading unpacked ZIPs

loader/mod_loader.gd
Now only shows the mod paths plus their load number, instead of the full JSON data. This makes it much easier to see the load order itself, without all the extra data.
This fix also stops the full JSON data from being duplicated. As before, the full JSON is still shown, via the `dev_log` just before the end of `_init`.
Preview:
Before:
=> Improve logging of mod_loader_order

README.md, loader/mod_loader.gd
Renames:
- `ModMain.gd` -> `mod_main.gd`
- `_meta.json` -> `manifest.json`
=> Rename to "mod_main.gd" and "manifest.json"

README.md, loader/mod_loader.gd
**Changes:**
- Updates the list of required manifest.json keys, to match the requirements of Thunderstore (see [issue](https://github.com/GodotModding/godot-mod-loader/issues/20#issuecomment-1380174626) / [Thunderstore docs](https://thunderstore.io/package/create/docs/))
- Logging: Puts every missing key onto its own file, improving readability
- Logging: Fixes a code error where the missing keys array wasn't cleared, causing missing keys to be duplicated in the logs
**Preview:**
**Related:**
- #20
- #26
=> Update manifest key validation to match Thunderstore requirements

README.md, loader/mod_loader.gd
Fixes a const that should have been renamed in PR #27:
`REQUIRED_META_TAGS` -> `REQUIRED_MANIFEST_KEYS_ROOT`
=> Fix manifest keys const name error in PR #27

loader/mod_loader.gd
Fixes another error in PR #27:
Parts of `mod_loader.gd` that use the mod ID needed to be updated to use `extra.godot.id` instead.
=> Fix not getting mod ID from `extra.godot.id` in PR #27

loader/mod_loader.gd
Adds a cli argument that allows for thunderstore to specify different mod folders path in different profiles.
=> Add cli argument for mod folder path

loader/mod_loader.gd
Prevents issues when the target JSON does not exist, returning an empty dictionary instead. You can use `dict.size() < 1` to check for this.
=> Return an empty dictionary on error for `_get_json_as_dict`

loader/mod_loader.gd
Add "namespace" as a required tag, for Thunderstore compatibility
=> Add required tag: `namespace`

README.md
I've started the [Wiki](https://github.com/GodotModding/godot-mod-loader/wiki). This update removes the stuff that's been added to it so far. I've kept the basics.
=> Migrate bulky README content to Wiki

loader/mod_loader.gd
Renames the dev logging CLI arg. It's now more indicative of its purpose.
=> Rename CLI arg `mod-dev` to `log-dev`

loader/mod_loader.gd
Makes `add_translation_from_resource` log the resource path.
Previously it only logged that a translation was added, with no indication on where it came from
=> Log resource path in `add_translation_from_resource`

loader/mod_loader.gd
Fix not using camelcase for `save_scene`
=> Fix not using camelcase for `save_scene`

README.md, loader/mod_loader.gd
Note: I've tested this extensively, incl. with the CLI args, so there shouldn't be any issues or errors unless I've completely missed something
**Config JSONs**
- Adds support for per-mod config JSONs in `res://configs`. View the README for full details.
- Provides a new utility func `get_mod_config(mod_id, key)`.
- This can be used to get the full data, or data from a specific key.
- Includes extensive validation, with error messages and codes listed in the README.
- Supports setting default options via a new required manifest key, `config_defaults`. 
- If set, using `get_mod_config` when no custom JSON file is present will return your manifest's defaults instead.
- Includes support for overwriting the configs dir with a CLI arg, `--configs-path`.
- Follows the precedent set by of #28.
- …
=> Config JSON

loader/mod_loader.gd
Changes:
- Removes `extra.godot.id`
- Validates that the mod ID is `{namespace}-{name}`. The mod won't load if it doesn't match
This works towards #20 ([this comment](https://github.com/GodotModding/godot-mod-loader/issues/20#issuecomment-1380166316)):
> tightly coupling the mod ID to package ID end to end would be great (so making them match with Thunderstore IDs to benefit from the ecosystem guarantees)
Logged error:
*^ note: I added that line break afterwards, to make it easier to preview here. There's no line break in the actual code*
=> Remove `id` meta tag and validate mod ID

README.md
Remove `id` from the README's example JSON
This should have been done in #51 but was missed
=> README - remove `id` from example json

README.md
I have migrated all the README content to the [wiki](https://github.com/GodotModding/godot-mod-loader/wiki), which now has a proper "Getting Started" section.
I've also duped the wiki's Getting started section to the readme, so visitors have an entry point and the readme doesn't look bare.
Preview:
https://github.com/ithinkandicode/godot-mod-loader/tree/readme-basic-v2
=> README - Migrate content to wiki

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_details.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_manifest.gd
for better type safety and convenience
this is only internal, nothing needs to be changed in mods.
@ithinkandicode check if this works for you to also integrate the config stuff
also closes #54
=> serialize into ModData and ModDetails 

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
This needs to be merged after 
- #60 
Breaking changes:
Removed:
```
ModLoader.
mod_log
dev_log
```
Use the following instead:
```
ModLoaderUtils.
log_fatal()
log_error()
log_warning()
log_info()
log_success()
log_debug()
log_debug_json_print()
```
closes #21
=> Split off logging and utils

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
Needs to be merged after 
- #62 
No breaking changes
Moves other utility functions from ModLoader and ModData to new ModLoaderUtils class. 
Only affects internal methods
=> Move other utils

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_manifest.gd
Fixes a few bits where `.mod_manifest` was used instead of `.manifest`
Also fixes the `get_mod_config` func not working. It still needs an update, but this stops it crashing
=> Minor fixes to `manifest`

addons/mod_loader/mod_loader.gd
Adding counts to debug number of unzipped and loaded mods by the mod loader
=> Add counts for debug purposes

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
nothing breaking, one refactor, one fix, one better log
=> smaller fixes for utils json as dict

addons/mod_loader/mod_loader_utils.gd
new command line arg to filter the output to relevant things
usage: `--log-ignore=["ModLoader","ModLoader:ModData","TestMod"]`
=> add command line arg to ignore specific log names

addons/mod_loader/mod_loader_utils.gd
should cover no flag and any flag. spaces still do not work due to godot splitting them.
new format: `--log-ignore=ModLoader,ModLoader:ModData,TestMod` (no spaces, no quotation marks)
=> fix log-ignore flag

addons/mod_loader/mod_loader_utils.gd, addons/mod_loader/mod_manifest.gd
Used log_fatal everywhere because the mod won't be loaded with these things being invalid. Avoids missing the error in the console and wondering why the mod did not load
=> Fix missing logging in mod manifest

addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/mod_loader_utils.gd
Use this startup flag to enable the self setup `--script addons/mod_loader/mod_loader_setup.gd`
Changes will apply after one restart. Setup was successful when the window name shows `(Modded)`
If the ModLoader autoload is already registered in the ProjectSettings, setup will be skipped - remove it when testing the setup.
As discussed before and in this [Godot proposal #6137](https://github.com/godotengine/godot-proposals/discussions/6137) here, the mod loader will end up as the last autoload when set up this way. 
That is completely fine for all mods that do not modify autoloads.
Mods that do modify autoloads will not work properly. To use those mods, you will still have to decompile the game and add it as the first autoload manually.
salvaged from #33
closes #8
=> Self setup

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
**Let mod authors create the ``overwrites.gd`` at the root of the mod folder**
- My current proposed solution on how to handle the overwrites
- Mod authors create the ``overwrites.gd`` script and ``overwrites`` folder in there mod folder:
- We provide tooling to make the creation of the ``overwrites.gd`` script a one click thing
- Tooling will be developed in the [Mod Tools Repo](https://github.com/GodotModding/godot-mod-tools)
- People ho don't want to use extra tooling can just write the ``overwrites.gd`` them self
``overwrites.gd`` from example mod:
```python
extends Node
func _init():
var overwrite_0 = preload("res://mods-unpacked/KANA-OverwritesTest/overwrites/assets/images/GodotModded.png")
overwrite_0.take_over_path("res://assets/images/GodotModded.png")
```
**Example Mod with this …
=> Add overwrite functionality

addons/mod_loader/mod_loader_setup.gd
Fixes a fatal typo, where `modloaderutils` was written as `ModLoaderUtils`.
=> Fix typo with `modloaderutils`

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/mod_loader_utils.gd, addons/mod_loader/mod_manifest.gd
- [fix not storing returned value in a variable for certain methods](https://github.com/GodotModding/godot-mod-loader/commit/db85341d4cc61b407e91065e5864abb0fd4aa55f)
- [fix errors due to func args having the same name as local vars](https://github.com/GodotModding/godot-mod-loader/commit/9d76b26a17aad98823926ec0ffabad3de49954c9)
=> Fix lint issues

addons/mod_loader/mod_loader.gd
It was missing `not`, which caused a crash if any mods did have a missing dependency.
=> Fix typo in `_handle_missing_dependency`

addons/mod_loader/mod_loader.gd
Adds a constant called `MODLOADER_VERSION` to the main file, *mod_loader.gd*.
Also removes the docs that listed the old version. This new constant can be the single source of truth.
I've set it to `4.2.0`. The next release might not be 4.2 exactly, but I think it's important to have the version higher than the last release from `main` so that if you download from develop, you can easily tell the difference as you'll be on a version that's not the last release version.
=> Add version constant

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
fix: prevent duplicate global class registration
refactor: utils global class registration does not save anymore, mod_loader exposes a new method for mods to use it and save
=> Fix global class registration

addons/mod_loader/mod_loader.gd
Asserts that ModLoader is the first autoload. 
The error messages aim to be as helpful as possible, and change depending on if you're in the editor or not.
Also logs the autoloads, via code by @KANAjetzt (originally from his PR #81).
Closes #87
=> Assert modlaoder is first autoload

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_manifest.gd
Validates dependencies and incompatibilities, checking the following for any specified mod IDs:
- Contains one `-`
- At least 7 characters (since both name and namespace must be 3+ characters)
- Name & namespace have valid names (via the regex in #60)
Closes #23
=> Validate dependencies and incompatibilities

addons/mod_loader/mod_loader_setup.gd
*Needs to be merged after [#89 ](https://github.com/GodotModding/godot-mod-loader/pull/89)*
Adds cmd arg:
-  `--only-setup`
Allows to setup the mod loader without user notification, or auto restart ( upcoming PR ).
Request from Mythic ( Thunderstore ):
> Mythic — 30/01/2023 09:39
how about would it be possible to support running just the installation step without restarting, but rather shutting down once it's complete?
that way we can use that as the "installer" on the manager, and you don't need to worry about CLI arg handling in the restart phase
> Mythic — 30/01/2023 09:43
and if that can return an appropriate exit code, (0 for success, non-zero for fail), that'd be great too
then we can have the manager just run that for install
=> --only-setup cli arg

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
Every game start now gets their own log and they are kept up to the same limit set for the vanilla game (5 usually)
- closes #16
=> store log backups and rotate them like godot

addons/mod_loader/mod_data.gd
Logging the full *manifest.json* for every mod floods the logs, and always means the Godot console says "show less text".
This minor tweak changes it to log the contents as a single line instead.
There's also a const option (`USE_EXTENDED_DEBUGLOG`) to log the full contents, as it may still be helpful during development.
=> Reduce manifest.json debug log length

addons/mod_loader/mod_loader_utils.gd
Currently `log_fatal` does not log to the file, which means it doesn't get added to *godot.log* during mod development.
Note: The current `"error"` condition uses both `printerr` and `push_error`. But I've only added `push_error` to the `"fatal-error"` condition, because `push_error` seems to print the error by itself (including the `ERROR: ` prefix), making the use of `printerr` redundant. So we may want to remove `printerr` for the `"error"` condition too after this.
=> `log_fatal` - add the missing log to file

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/mod_loader_utils.gd
Adds cmd arg:
Forces the setup to create the ``override.cfg`` in the game base directory.
Skips the ``project.binary`` injection.
The project binary injection is skipped in that case.
```python
if is_setup_create_override_cfg:
handle_override_cfg()
else:
handle_project_binary()
```
=> --setup-create-override-cfg cli arg

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
Adds two functions to ModLoaderUtils so they can be used in `mod_loader.gd` and the setup script.
- `get_autoload_array() -> Array`
Get an array of all autoloads -> ["autoload/AutoloadName", ...]
- `get_autoload_index(autoload_name: String) -> int`
Get the index of a specific autoload
Updates code from #96 to use the new util.
Has to be merged after #99
=> Utils for ModLoader autoload position

addons/mod_loader/mod_loader_setup.gd
Removes the `ProjectSettings` based check for successful installation and adds a check based on the ModLoader autoload position.
If the ModLoader autoload is not detected as the first autoload the setup will be executed.
Includes some restructuring and removal of unneeded functions.
**EDIT
Just realized that a check for `--setup-create-override-cfg` is required.
Because the autoload will be the last one in that case.*
**EDIT2
After testing. 
Adding a check before  `_check_first_autoload()` in `mod_loader.gd` might be a good idea.
---
Has to be merged after #104
=> Check modloader autoload position on setup

addons/mod_loader/mod_loader.gd
I figure the notice is most likely to be seen by modders in the editor, who won't be using the `mods` dir, so this would almost always be a misleading error
=> Downgrade the missing `mods` dir error to a warning

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_setup.gd
Prevents the setup script from running the setup again, if the mod loader was installed via the *override.cfg*.
Prevents the error logging in `_check_first_autoload()`, if a *override.cfg* file is present.
=> ✔ added checks for override.cfg setup

addons/mod_loader/mod_loader.gd
Checks that the file exists before trying to add it as a translation.
Closes #117
=> Validate file exists for `add_translation_from_resource`

addons/mod_loader/mod_manifest.gd
Added is_silent parameter to 
- `is_name_or_namespace_valid()`
- `is_semver_valid()`
- `validate_dependencies_and_incompatibilities()`
- `is_mod_id_valid()`
Can be used to not log an error if the validation returns `false`. Useful for example if the validation is used in a text input where the result will be most of the times `false`. Implemented with the [ModTool](https://github.com/GodotModding/godot-mod-tool) in mind.
**Sorry accidentally closed #128*
=> refactor: :recycle: Added is_silent parameter to validation functions

addons/mod_loader/mod_loader.gd
Title. No functional changes besides automatic whitespace cleanup.
=> Cleanup: Remove trailing whitespace

addons/mod_loader/mod_data.gd, addons/mod_loader/mod_manifest.gd
Removes a few "todo" comments. They'd be better as [issues](https://github.com/GodotModding/godot-mod-loader/issues) if we still want to implement them, as that would help us keep track of them better.
=> Cleanup: Remove todos

addons/mod_loader/mod_manifest.gd
Fixes infinite loops if a mod adds itself as a dependency. Also prevents mods from being listed as incompatible with themselves.
Closes #113:
- #113
=> Validation: Don't allow mods to include themselves as dependencies or incompatibilities

addons/mod_loader/mod_loader.gd
Swaps the status codes `1` and `2` around, so that a valid code is always `>= 1`. Also has a very minor presentation edit for the comments on the enums.
Closes #131:
- #131
=> Config JSON: Swap status codes 1 and 2 (closes #131)

addons/mod_loader/mod_loader_utils.gd
I saw this approach in a c# game I decompiled a while ago. It lets us show important notes that would otherwise be stripped when you decompile a game's PCK.
I don't know how useful it would be across the entire codebase, but I think that doing it for this one particular bit of code (`log_fatal`) would be very helpful to new users. Eg. I've seen a few people on the Brotato discord who didn't understand why they were getting an error here, because if you don't know about the error stack trace, it can look like an error with ModLoader itself.
It uses a dummy func, `code_note`, which does nothing but can be re-used elsewhere as it's part of `ModLoaderUtils`.
=> Misc: Add `code_note` func, to show a helpful message in `log_fatal`

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_utils.gd
**NOTE: Depends on PR #143, which should be merged first.**
Adds 3 methods to `ModLoader`. There's 2 for saving data, plus a small utility method for checking if a config JSON data object is valid.
```gdscript
func is_mod_config_data_valid(config_obj: Dictionary) -> bool:
func save_mod_config_dictionary(mod_id: String, data: Dictionary, update_config: bool = true) -> bool:
func save_mod_config_setting(mod_id: String, key:String, value, update_config: bool = true) -> bool:
```
Docs: https://github.com/GodotModding/godot-mod-loader/wiki/Upcoming-Features#config-json
---
Closes #132:
- #132
=> Config JSON: Add API methods for saving data

addons/mod_loader/mod_loader_utils.gd
Adds two helpers for saving data to a file.
```gdscript
func save_string_to_file(save_string: String, filepath: String) -> bool:
func save_dictionary_to_file(data: Dictionary, filepath: String) -> bool:
```
Docs: https://github.com/GodotModding/godot-mod-loader/wiki/Upcoming-Features#saving
=> Utility: Add 2 funcs for saving data to files

addons/mod_loader/classes/mod_data.gd, addons/mod_loader/classes/mod_manifest.gd, addons/mod_loader/mod_loader_utils.gd
Moves `class_name` to come before `extends`. This follows Godot's [style guide](https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/gdscript_styleguide.html), and makes all our classes follow the same convention.
=> Refactor: Move `class_name` to be before `extends`

addons/mod_loader/classes/mod_manifest.gd
Can be used to get a dictionary of the Manifest data, will be used by the Mod Tool.
=> feat: :sparkles: Added `get_as_dict()` function to ModManifest Class

addons/mod_loader/classes/mod_manifest.gd
Added type check to `_get_string_from_dict()` and  `_get_array_from_dict()`
=> refactor: :recycle: ModManifest - Added type checks

addons/mod_loader/classes/mod_manifest.gd
Added `compatible_mod_loader_version` to manifest data. This field has been changed from a single `String` to a `PoolStringArray` for parity with other version fields. Added handling for this change and deprecation warning.
- Single String value for `compatible_mod_loader_version` deprecated
=> refactor: ♻️ Added compatible_mod_loader_version to manifest data

addons/mod_loader/classes/mod_manifest.gd
fix typo in `is_mod_id_valid()` no hyphen `log_fatal()` error message.
=> fix: :pencil2: fix typo hypen -> hyphen

addons/mod_loader/classes/mod_manifest.gd
splited `validate_dependencies_and_incompatibilities()` in to `validate_dependencies()`, `validate_incompatibilities()` and `is_mod_id_array_valid()`. Will be used in the ModTool to validate the fields separately.
=> refactor: :recycle: split off dep and inc validation function

addons/mod_loader/classes/mod_manifest.gd
**❌ - Merge after #170**
Added `is_semver_version_array_valid()` to check an array of semver versions. For example the *compatible_mod_loader_version* field.
=> ❌Added `is_semver_version_array_valid()`

addons/mod_loader/classes/mod_manifest.gd
Can be used to retrieve the Manifest values as JSON, in the *manifest.json* format. Will be used in the Mod Tool.
=> feat: :sparkles: ModManifest - Added `to_json()` function

addons/mod_loader/api/config.gd, addons/mod_loader/api/godot.gd, addons/mod_loader/api/third_party/steam.gd, addons/mod_loader/classes/options_profile.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/mod_loader_store.gd, addons/mod_loader/mod_loader_utils.gd, addons/mod_loader/options/profiles/current.tres, addons/mod_loader/options/profiles/default.tres, addons/mod_loader/options/profiles/disable_mods.tres, addons/mod_loader/options/profiles/production_no_workshop.tres, addons/mod_loader/options/profiles/production_workshop.tres
Adds a new singleton called `ModLoaderStore`, which comes before `ModLoader` in the autoload order. This new singleton is a data store, and lets us reference data that was previously held as local vars in ModLoader, and which therefore may not have been accessible to all methods due to ModLoader not being initialised during its `_init()` phase.
I have implemented the following:
- Create the new ModLoaderStore singleton _(closes [#161](https://github.com/GodotModding/godot-mod-loader/pull/146))_.
- Moved some local variables from `ModLoader` to `ModLoaderStore` _(closes [#161](https://github.com/GodotModding/godot-mod-loader/pull/146))_.
- Implemented the path override options that were missing from the recent ML Options work _(follows …
=> feat: ✨ ModLoaderStore: New singleton to store data

addons/mod_loader/mod_loader.gd
Fixes a minor typo in a comment
=> fix: ✏️ Fix typo: `improt` -> `import`

addons/mod_loader/classes/mod_manifest.gd
This will make the generated JSON a lot more readable if it is saved to a file.
=> style: :art: Add `\t` indent to `JSON.print()`

addons/mod_loader/classes/mod_manifest.gd, addons/mod_loader/mod_loader_utils.gd
Moves `_get_string_from_dict()`,  `_get_array_from_dict()` and  `dict_has_fields()` from *mod_manifest.gd* to *mod_loader_utils.gd*
*closes #165*
=> refactor: :recycle: Move utility funcs out of *mod_manifest.gd*

addons/mod_loader/mod_loader.gd
Before this fix, it was possible to trigger an infinite loop in the dependency check if two mods declared each other as dependencies. Now, the dependency chain is tracked inside the `dependency_chain` array. If the same mod ID is detected, the loop will break.
closes #111
=> fix: :bug: circular dependency check

addons/mod_loader/mod_loader.gd
Instead of returning if a circular dependency is detected, the loop should continue with the next entry.
=> fix: :bug: continue check if circular dep is detected

addons/mod_loader/classes/mod_manifest.gd, addons/mod_loader/mod_loader.gd
The code from 
- #115 
Adds functionality to specify a mod you want to load before your own mod. 
Load before field added to  *manifest.json* in *extra* -> *godot* -> *load_before*
For example:
`"load_before": ["Darkly77-ContentLoader"],`
```JSON
{
"name": "WhatAmILookingAt",
"namespace": "KANA",
"version_number": "1.0.0",
"description": "Tells you where this thing is from.",
"website_url": "https://github.com/BrotatoMods",
"dependencies": [],
"extra": {
"godot": {
"incompatibilities": [],
"load_before": ["Darkly77-ContentLoader"],
"authors": ["KANA"],
"compatible_mod_loader_version": "4.3.0",
"compatible_game_version": ["0.8.0.3"],
"config_defaults": {}
}
}
}
```
Will need some more testing, this is just a naive implementation.
---
closes #114 
---
- Mods added to `load_before` should …
=> feat: :sparkles: added load_before

addons/mod_loader/classes/mod_manifest.gd, addons/mod_loader/mod_loader.gd
Added new loop that iterates through each mod in `mod_data` and runs `_check_dependencies()` with a new `is_required` flag set to `false`. This flag is used to determine the dependency array to use and if a mod is still loaded if the dependency is missing.
closes #122
=> feat: :sparkles: Added optional dependencies

addons/mod_loader/classes/mod_manifest.gd
Adds validation function `validate_dependencies_and_incompatibilities_conflicts()` to *mod_manifest.gd*
Validates a mod's `dependencies` and `incompatibilities` to ensure they don't conflict.
closes #169
=> fix: ♻️ ModID in `dependencies` and `incompatibilities`

addons/mod_loader/classes/mod_manifest.gd
Using `is_mod_id_array_valid()` for `dependencies` `optional_dependencies` and `incompatibilities`
closes #190
=> refactor: :recycle: split validation functions

addons/mod_loader/classes/mod_manifest.gd
- reworked `validate_dependencies_and_incompatibilities_conflicts()` to work with any arrays
-  renamed it to `validate_distinct_mod_ids_in_arrays()`. 
- Fixed the accidentally removed function call of `validate_dependencies_and_incompatibilities_conflicts()` in `_init()`
- Added validation to check for distinct mod_ids in `incompatibilities` and `optional_dependencies`.
closes #192
=> refactor: :recycle: `validate_distinct_mod_ids_in_arrays()`

addons/mod_loader/classes/mod_manifest.gd
Checks if the same mod id is in
- `load_before` <-> `dependencies` 
- `load_before` <-> `optional_dependencies`
closes https://github.com/GodotModding/godot-mod-loader/issues/187
=> feat: ✨ Added validation for load_before

addons/mod_loader/classes/mod_manifest.gd
Adds a `is_mod_id_array_valid()` func call for `load_before` to the `_init()` func.
*closes #186*
=> refactor: :recycle: Check for valid mod ids in `load_before`

addons/mod_loader/mod_loader_utils.gd
- Adds `const MOD_CONFIG_DIR_PATH := "user://configs"` to *mod_loader_utils.gd*
- Updates `get_path_to_configs()` to use `MOD_CONFIG_DIR_PATH`
breaking: Any custom configs stored in `res://configs` will no longer be loaded. 
closes #167
=> refactor: :recycle: changed mod config dir path to `user://configs`

addons/mod_loader/mod_loader.gd
Adds `_reset_extension()` so that an extension can be reset to the default state of the base godot project script, we save the base scripts when extending one, all the scripts saved are saved in order of calling, this is the base for the subsequent prs that will allow for easy mod updating and disabling at runtime
=> feat: added _reset_extension

addons/mod_loader/mod_loader.gd
Requires: https://github.com/GodotModding/godot-mod-loader/pull/195
Adds `_remove_extension` that allows for removal of a specific extension, this resets the base script and then reinstalls all the other extensions in the already sorted order
=> feat: added _remove_extension

addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/mod_loader_utils.gd
In #172 the ModLoaderUtils utility functions were updated to use the ModLoaderStore singleton. 
However, this caused an issue with the self-setup script, as the setup was getting stuck in an infinite loop due to the `ModLoaderStore` not being initialized yet. 
To resolve this issue, `get_modloader_store()` was added to *mod_loader_utils.gd*, which returns a reference to the `ModLoaderStore` singleton if it exists or `null` otherwise.
This functions use it now:
- `_get_verbosity()`
-  `get_path_to_mods()`
-  `get_path_to_configs()` 
Additionally, the `autoload index` check in the `_init()` function of *mod_loader_setup.gd* was updated to check for the right indexes of `ModLoader` and `ModLoaderStore`.
Tested with and without `--setup-create-override-cfg` .
closes #200
=> fix: :bug: self setup chicken and egg problem

addons/mod_loader/classes/mod_manifest.gd
really simple check for length 3
@ithinkandicode do we really need all of that `type` stuff at the beginning of the method? what was the intended use for that and will that be followed up upon?
=> Fix mod id validation

addons/mod_loader/api/deprecated.gd, addons/mod_loader/classes/options_profile.gd, addons/mod_loader/mod_loader_store.gd
Slightly refactors `ModLoaderDeprecated` to support a new ML Option, which downgrades the fatal errors from deprecated methods to just warnings.
This is mainly to help existing mods transition to ML v6, considering major breaking changes like #208.
_Note: I know we agreed to concat strings with `+`  instead of `str` (in #166), and this file still uses `str`, but that can be handled in a different PR as this one is only focused on this feature._
=> feat: Option to skip deprecated fatal error

addons/mod_loader/mod_loader.gd
This enables people to reload mods at runtime, currently the only changes made by mods that will be reset by this are extensions, which is the major changing factor in most cases. Opens up for next PRs that can reset nodes and hopefully all changes that mod developers want to make. 
An example use case scenario would be: user downloads or updates mod, without needing to restart the whole game, the user could click a button in game that reloads all mods. Another example could be a mod that introduces in game mod downloading and updating, allowing for a better user experience.
This PR also renames 
`_remove_extension` > `_remove_specific_extension_from_script` and 
`_reset_extension` > `_remove_all_extensions_from_script` for easier functionality comprehension.
Adds a fix for #198 that …
=> feat: mod reloading

addons/mod_loader/api/mod.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/mod_loader_store.gd
Moves the main funcs from `ModLoader.method` to `ModLoaderMod.method`, as discussed in #153.
Some vars had to be moved from `ModLoader` to `ModLoaderStore`: `is_initializing` and `script_extensions`.
Includes deprecated funcs in the main ModLoader file. Developed alongside #207 (which downgrades the inevitable flood of fatal errors to just warnings).
**Related:**
- #153
- #207
=> refactor: Move main mod API funcs to `ModLoaderMod`, from `ModLoader`

addons/mod_loader/mod_loader.gd
Mods should not pass the dependency check if one of there dependencies are not loadable.
=> fix: :bug: check if a mod `is_loadable`

addons/mod_loader/api/config.gd, addons/mod_loader/api/log.gd
Depends on #205
Adds an arg to all the log methods that let you only log the message once.
closes https://github.com/GodotModding/godot-mod-loader/issues/141
=> feat: ✨ Added `only_once` parameter to all log funcs

addons/mod_loader/mod_loader_setup.gd, addons/mod_loader/setup/setup_log.gd, addons/mod_loader/setup/setup_utils.gd
The tradeoffs of utilizing the existing ModLoader Classes in the setup script are too significant. So the required functions where moved into the *setup/* dir and any dependencies to other classes where removed.
=> refactor: :recycle: created *setup_log.gd* and setup_utils.gd*

test/Unit/test_manifest_validation.gd
Tests for:
- `is_mod_id_valid()` by @Qubus0 
- `validate_distinct_mod_ids_in_arrays()`
- `test_is_mod_id_array_valid()`
=> test: :white_check_mark: tests for manifest validation

.gitattributes
To provide the mod loader on the Godot AssetLib we need to get rid of any third-party dependencies. Fortunately, we only need these tools for the self setup.
=> chore: Add `.gitattributes` to allow AssetLib downloads

addons/mod_loader/api/config.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
This moves `mod_data` from *mod_loader.gd* to *mod_loader_store.gd*, enabling easier access from different classes.
- Two mods in my list, because they directly access `ModLoader.mod_data`.
`if ModLoader.mod_data.keys().has("damiBenro-Junker")`
- The default mod menu in Brotato for the same reason.
`for key in ModLoader.mod_data:`
Opened #219 and #221 to prevent this in the future. 
<br />
<br />
---
*works towards #153*
=> refactor: :recycle: Move `mod_data` `ModLoader` -> `ModLoaderStore`

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
This moves `mod_load_order` from *mod_loader.gd* to *mod_loader_store.gd*, enabling easier access from different classes.
<br />
<br />
*works towards #153*
=> refactor: :recycle: Move `mod_load_order` to `ModLoaderStore`

addons/mod_loader/api/mod.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
Moves the remaining vars from *mod_loader.gd* to *mod_loader_store.gd*.
- `_saved_objects` ( renamed to `saved_objects` )
- `loaded_vanilla_parents_cache`
- `_saved_scripts` ( renamed to `saved_scripts` )
<br />
<br />
*works towards #153*
=> refactor: ♻️ move remaining vars to `ModLoaderStore`

addons/mod_loader/classes/mod_data.gd, addons/mod_loader/internal/cli.gd, addons/mod_loader/internal/dependency.gd, addons/mod_loader/internal/file.gd, addons/mod_loader/internal/godot.gd, addons/mod_loader/internal/mod_loader_utils.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd, addons/mod_loader/setup/setup_utils.gd
Updated all files to match the naming convention we agreed upon in #227.
=> style: ✏️ rename funcs to match naming convention

addons/mod_loader/api/mod.gd, addons/mod_loader/internal/path.gd, addons/mod_loader/internal/script_extension.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
Not sure if we should do this. Moving `const UNPACKED_DIR` will break a lot of Brotato Mods because they use this pattern in there *mod_main.gd* most of the time:
`dir = modLoader.UNPACKED_DIR + "Darkly77-ContentLoader/"`
And I don't think there is a good way to add a deprecation warning to a `const`?
---
- Moved to `ModLoaderStore`:
- `MODLOADER_VERSION`
- `DEBUG_ENABLE_STORING_FILEPATHS`
- `UNPACKED_DIR`
- `REQUIRE_CMD_LINE`
- Added `get_unpacked_dir()` to `ModLoaderMod`
- Added `get_unpacked_mods_dir_path()` to `_ModLoaderPath`
<br/>
*works towards https://github.com/GodotModding/godot-mod-loader/issues/153*
=> refactor: ♻️ move consts from `ModLoader` to `ModLoaderStore`

addons/mod_loader/api/profile.gd, addons/mod_loader/internal/script_extension.gd, addons/mod_loader/mod_loader.gd
- Corrected an error in `ModLoaderUserProfile` where `UNPACKED_DIR` was incorrectly referenced to `ModLoader`.
- Updated all other references to `UNPACKED_DIR` to use `_ModLoaderPath.get_unpacked_mods_dir_path()`
- Removed the comment that was added to `handle_script_extensions()` function before the `UNPACKED_DIR` const was moved to `ModLoaderStore`.
=> fix: 🐛 wrong `UNPACKED_DIR` reference

addons/mod_loader/internal/script_extension.gd
This was missed when changing utility method locations
=> fix: Missed ModLoaderUtils to _ModLoaderFile change

addons/mod_loader/api/mod.gd
- adds `is_mod_loaded(mod_id: String) -> bool` to `ModLoaderMod` to check if a Mod is loaded
<br />
<br />
closes #219
=> feat: :sparkles: added `is_mod_loaded()`

.gitmodules, addons/mod_loader/api/config.gd, addons/mod_loader/api/profile.gd, addons/mod_loader/classes/mod_config.gd, addons/mod_loader/classes/mod_data.gd, addons/mod_loader/classes/mod_manifest.gd, addons/mod_loader/internal/cache.gd, addons/mod_loader/internal/file.gd, addons/mod_loader/internal/mod_loader_utils.gd, addons/mod_loader/internal/path.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
This PR introduces a comprehensive rework of the Mod Config setup, addressing the requirements outlined in issue #178. Key changes include the addition of `JSONSchema` Validation and the implementation of a new `Resource` Class called `ModConfig`, which defines the structure of the Config Data. The existing `ModLoaderConfig` has been completely rewritten, offering new API methods that cater to the various needs of creating a UI for editing Mod Configs and integrating them within a Mod Project.
- `create_config(mod_id: String, config_name: String, config_data: Dictionary) -> ModConfig`
Creates a new configuration for a mod, stores it in the mod's `ModData` and saves it to a new config JSON file in the mod's config directory.
- `update_config(config: ModConfig) -> ModConfig`
Updates an …
=> feat: ✨ Advanced Mod Configs

addons/mod_loader/internal/file.gd, addons/mod_loader/internal/path.gd, addons/mod_loader/internal/third_party/steam.gd, addons/mod_loader/mod_loader.gd
1. Moved `_load_steam_workshop_zips()` from `ModLoader` to `_ModLoaderSteam` - rename to `load_steam_workshop_zips()`
2. ~Moved `_load_mod_zips()` from `ModLoader` to `_ModLoaderFile` - rename to `load_mod_zips()`~
**Moved `_load_mod_zips()` back to `ModLoader` because of cyclic dependencies. `_ModLoaderSteam.load_steam_workshop_zips()` uses `_ModLoaderFile.load_zips_in_folder()`. This can be resolved with #256**
4. Moved `_load_zips_in_folder(folder_path: String)` from `ModLoader` to `_ModLoaderFile` rename to `load_zips_in_folder(folder_path: String)`
closes #153
=> refactor: 🚚 move funcs out of ModLoader

addons/mod_loader/mod_loader.gd
Currently the mod loader will try to read hidden directories (such as .git) as if they were mods and then throw assertion errors. This just adds a small check to stop that
=> refactor: ♻️ Ignore hidden directories

addons/mod_loader/classes/mod_manifest.gd
- Removes `"incompatibilities"` from `REQUIRED_MANIFEST_KEYS_EXTRA`
No need to pass an empty array if you don't need it. 
<br/>
closes #242
=> refactor: :recycle: remove `incompatibilities` from required keys

addons/mod_loader/internal/mod_loader_utils.gd
- removed reference to manifest in the error message because it is now in the general utils.
closes #253
=> fix: :pencil2: removed reference to manifest in error message

addons/mod_loader/classes/options_profile.gd, addons/mod_loader/internal/godot.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
To make things work when `ModLoaderStore` is not placed before `ModLoader`, I had to move the check to the beginning of the `_init()` function. To handle the problem in `check_autoload_order()`, where I couldn't use `ModLoaderLog.fatal()` due to its reliance on a function that references `ModLoaderStore`, I directly loaded the ModLoader Options resource in `_check_autoload_positions()`. Check out issue https://github.com/GodotModding/godot-mod-loader/issues/262 for more info.
Did the same fix for `check_autoload_position()` to allow the error logging without `ModLoaderStore`
<br/>
<br/>
closes #257
closes #262
=> feat: ✨ option to allow autoload placement anywhere

addons/mod_loader/api/config.gd, addons/mod_loader/api/profile.gd, addons/mod_loader/classes/mod_data.gd, addons/mod_loader/classes/mod_user_profile.gd, addons/mod_loader/mod_loader_store.gd
This will make it easier to access all profile data of the current profile. Before, you always had to get the profile data from `ModLoaderStore.user_profiles`.
- Removed the sub Class `Profile` in `ModLoaderUserProfile`
- Added new Resource Class `ModUserProfile`
To allow setting the type in `ModLoaderStore` without causing a cyclic dependency.
<br/>
<br/>
closes #247
=> refactor: :recycle: store Profile object instead of  profile name

addons/mod_loader/internal/path.gd, addons/mod_loader/resources/mod_manifest.gd
With this change, these functions will always return the full path to the config file/dir, even if the parent directory doesn't exist. Usually, this directory will be created later when the file is saved.
closes #267
=> fix: :bug: removed `dir_exists()` check

addons/mod_loader/internal/third_party/steam.gd
Fixed a bug where the path to the steam workshop directory was not set correctly.
=> fix: :bug: wrong steam workshop directory path

addons/mod_loader/api/deprecated.gd
There seems to be an issue where deprecations can cause mods to stop working even through the `assert` from `log-fatal` should be removed. 
To circumvent this, turn all deprecations into warnings for standalone (non-editor) builds
=> fix: always use warnings for deprecations in standalone builds

addons/mod_loader/api/log.gd
Previously, the same log entry was only saved to the previous entry in `ModLoaderStore.logged_messages.all[logMD5]`. This change adds a check for an `existing_entry` and adds to the entry stacks in `ModLoaderStore.logged_messages.by_mod` and `ModLoaderStore.logged_messages.by_type`.
=> fix: :bug: log stack only saved for `logged_messages.all`

addons/mod_loader/api/config.gd, addons/mod_loader/api/deprecated.gd, addons/mod_loader/api/log.gd, addons/mod_loader/api/mod.gd, addons/mod_loader/api/profile.gd
Rewrote comments in the following classes to facilitate automatic API documentation generation using [gdscript-docs-maker](https://github.com/GDQuest/gdscript-docs-maker):
- ModLoaderConfig
- ModLoaderDeprecated
- ModLoaderLog
- ModLoaderMod
- ModLoaderUserProfile
The goal is to further extend this to include the Resource classes and potentially the internal classes as well.
<br/>
<br/>
works towards #254
=> docs: 📝 Rewrote API class comments

addons/mod_loader/internal/script_extension.gd, addons/mod_loader/mod_loader_store.gd
The current algorithm returns a random result unless a is in b's type hierarchy.  Random results are disallowed in the sort_custom API
https://docs.godotengine.org/en/3.5/classes/class_array.html?highlight=sort_custom
The new algorithm sorts alphabetically by names in the type hierarchy paths until one of the trees stop then it sorts the shorter tree first.
Aims to fix the following errors that gets spammed at startup (and i think causes startup crashes):
E 0:00:00.815   SortArray<class Variant,struct _ArrayVariantSortCustom,1>::partitioner: bad comparison function; sorting will be broken
<C++ Source>  .\core/sort_array.h:179 @ SortArray<class Variant,struct _ArrayVariantSortCustom,1>::partitioner()
<Stack Trace> script_extension.gd:39 @ handle_script_extensions()
mod_loader.gd:164 @ …
=> fix: Transitive Comparator for script sorting 

addons/mod_loader/api/mod.gd, addons/mod_loader/api/mod_manager.gd, addons/mod_loader/mod_loader_setup.gd
Moved the methods handling mod state from `ModLoaderMod` to `ModLoaderModManager`. Additionally, all getter methods inside `ModLoaderMod` have been moved together at the bottom.
closes #281
=> refactor: :truck: Moved methods handling mod state

addons/mod_loader/internal/mod_loader_utils.gd
ModLoaderUtils log deprecation messages all state the old method class was `ModLoader.*`, but this should be `ModLoaderUtils.*`. This fixes that.
Closes #299.
=> fix: :bug: Fix ModLoaderUtils log deprecation using `ModLoader.*`

addons/mod_loader/api/profile.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/resources/mod_data.gd
- Added `is_active` property to `ModData`.
- Removed the section in `_update_mod_list()` that enables mods that are in `ModLoaderStore.mod_data` 
(previously disabled mods did not end up in `ModLoaderStore.mod_data`).
**Breaking Change:**
With the recent update, mods are now always unpacked and loaded into `ModLoaderStore.mod_data`. This change can potentially break Mod Lists that rely on having only loaded mods in `mod_data`. Consequently, these Mod Lists may display mods that are currently not loaded. To address this issue, authors of Mod Lists need to adapt their code to check the new `is_active` flag for each mod.
<br/>
<br/>
closes #286
=> refactor: :recycle: reworked disabling mods via user profile

addons/mod_loader/api/profile.gd, addons/mod_loader/internal/file.gd, addons/mod_loader/internal/path.gd, addons/mod_loader/internal/third_party/steam.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd, addons/mod_loader/resources/mod_data.gd
- Added `zip_name` and `zip_path` to `ModData`
- The functions responsible for loading zip files now return a dictionary containing the zip data:
```gdscript
zip_data = {
"mod_id": "path/to/zip/file.zip"
}
```
- New util `ModLoaderPath.get_dir_paths_in_dir()`
*Used in `load_zips_in_folder()` to map the zip file path to the correct mod.*
- User Profiles now store the path to the zip file associated with each mod
- Issue #288 has been resolved by implementing a check to verify the existence of the mod's zip file. 
*c587953b3bde8584e95ca85f50aa5918a9fc7aa6 Note: This allows to verify if the mod is still installed by confirming the existence of the zip file. However, this check is only performed when the mod is not loaded and a path to the zip file exists. This ensures that mods are not …
=> refactor: ♻️ reworked mod uninstall detection

addons/mod_loader/internal/path.gd
It can be confusing when the assert is triggered in the utility function, as the error message is naturally more generic. Reducing it to just "error" allows the calling function to assert and provide a more detailed error message.
=> refactor: :recycle: lowered the log level from fatal to error

addons/mod_loader/api/profile.gd, addons/mod_loader/internal/file.gd, addons/mod_loader/mod_loader.gd
Refactored `_update_mod_list()` by adding the missing `.keys()` call, removing the outdated check for uninstalled mods, and implemented an if statement in `_setup_mods()` within *mod_loader.gd* to prevent initializing `mod_data` twice, which resolves the issue of the missing `zip_data`.
closes #306
=> fix: :bug: `ModData` init and uninstall detection

addons/mod_loader/resources/mod_manifest.gd
Added validation to check for the same mod_ids in `optional_dependencies` and `dependencies`
**Breaking Changes:**
Technically, it may break mods that have the same `mod_id` listed in both the `optional_dependencies` and `dependencies` sections. However, since the `optional_dependencies` feature was introduced in v6.0.0, it is highly unlikely that such conflicts exist.
=> refactor: :recycle: unique ids `optional_dependencies` - `dependencies`

addons/mod_loader/resources/mod_manifest.gd
Added validation to check for the same mod_ids in `load_before` and `incompatibilities`
Breaking Changes:
Technically, it may break mods that have the same `mod_id` listed in both the `load_before` and `incompatibilities` sections. However, since the `load_before` feature was introduced in v6.0.0, it is highly unlikely that such conflicts exist.
=> refactor: :recycle: unique ids `load_before` - `incompatibilities`

.github/workflows/main.yml
- No longer prevent the `check_dependencies` task from running for release PRs.
=> ci: :recycle: no longer ignore the main branch

addons/mod_loader/api/log.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd, addons/mod_loader/options/options.tres, addons/mod_loader/options/profiles/editor.tres, addons/mod_loader/resources/options_current.gd
adds a dictionary for overrides based on feature tags to options.
I had to modify ModLoaderLog a little to avoid crashes when the store - and the options themselves in the store - are not available yet, which is the case in the options loading method.
needs to be documented on the options page after merge to main
```
```
https://docs.godotengine.org/en/3.5/tutorials/export/feature_tags.html
closes #296
=> feat: add dictionary for overrides based on feature tags to options

addons/mod_loader/api/profile.gd, addons/mod_loader/internal/file.gd
Demote the log message in `ModLoaderUserProfile` regarding "no `mod_ids` inside `mod_list`" from a warning to an info level. Similarly, demote the log message in `_ModLoaderFile` about "can't open mod folder" from an error to an info level. This adjustment is aimed at preventing confusion after the mod loader is running for the first time without any mods.
closes #327
=> refactor: :recycle: demote log messages

addons/mod_loader/api/log.gd, addons/mod_loader/mod_loader.gd
Before, it was only possible to match 100% of a log name to ignore it e.g. `ModLoader:Deprecated`. This can get tedious if you want to ignore all logs from a log name. 
Now you can use a wildcard at the end e.g. `ModLoader:*` to ignore all log names starting with that segment.
Resubmission of #331, since it got lost between branch resets somehow
- #331
=> feat: log name wildcards

addons/mod_loader/api/mod.gd, addons/mod_loader/internal/scene_extension.gd, addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd
**`static func refresh_scene(scene_path: String) -> void:`**
Refreshes a specific scene by marking it for refresh.
This function is useful if a script extension is not automatically applied. This situation can occur when a script is attached to a preloaded scene. If you encounter issues where your script extension is not working as expected, try to identify the scene to which it is attached and use this method to refresh it. This will reload already loaded scenes and apply the script extension.
🚨 `refresh_scene` will only work for Godot 4.3 and up. 🚨
**`static func extend_scene(scene_vanilla_path: String, edit_callable: Callable) -> void:`**
Extends a specific scene by providing a callable function to modify it. The callable receives an instance of the vanilla_scene as the first …
=> feat: :sparkles: adds `refresh_scene` and `extend_scene`

addons/mod_loader/internal/third_party/steam.gd, addons/mod_loader/mod_loader_store.gd, addons/mod_loader/resources/options_profile.gd
Allows storing the game's Steam ID in the Mod Loader Options. 
- Updated `_get_steam_app_id()` to check `ml_options` before attempting to retrieve the ID from `steam_data.json`.
=> feat: :sparkles: added `steam_id` to `ml_options`

addons/mod_loader/mod_loader.gd, addons/mod_loader/resources/mod_data.gd
- Added the `sources` enum to `ModData`. 
- Added the `get_mod_source()` function to  `ModData`. 
- Updated `_init_mod_data()` in `ModLoader` to set the mod source.
=> feat: :sparkles: store the mod source in `ModData`

addons/mod_loader/internal/path.gd, addons/mod_loader/resources/mod_manifest.gd
Added an optional field `steam_workshop_id` to `ModManifest`. 
In the editor, it is validated with a basic string length check. Once loaded from a workshop path, it's validated based on the `zip_path`. If invalid, it's overridden by the correct ID retrieved from the `zip_path`.
=> feat: :sparkles: added `steam_workshop_id` to `ModManifest`

addons/mod_loader/internal/path.gd
missed renaming `zip_path_global` to `zip_path` after removing the redundant path globalization in #393
=> fix: :bug: wrong var name

addons/mod_loader/mod_loader.gd, addons/mod_loader/mod_loader_store.gd, addons/mod_loader/options/profiles/production_no_workshop.tres, addons/mod_loader/options/profiles/production_workshop.tres, addons/mod_loader/resources/options_profile.gd
It has been replaced by the `load_from_steam_workshop` option in #369 
closes #384
=> refactor: :fire: removed `steam_workshop_enabled` option
